/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json.xml.converter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {}
}
